# Generated by Django 5.1.6 on 2025-08-10 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0002_alter_turf_details_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cancelled_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        default="cancelled", editable=False, max_length=10
                    ),
                ),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelled_bookings",
                        to="Turfapp.turf_details",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
