# Generated by Django 5.1.6 on 2025-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0003_cancelled_booking_delete_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AddField(
            model_name="turf_details",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("player", "Player"), ("owner", "Owner"), ("admin", "admin")],
                default="player",
                max_length=10,
            ),
        ),
    ]
