# Generated by Django 5.1.6 on 2025-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0004_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
