# Generated by Django 5.1.6 on 2025-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0006_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("confirmed", "confirmed"),
                    ("incomplete", "Incomplete"),
                    ("completed", "completed"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
