# Generated by Django 5.1.6 on 2025-08-30 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0008_customuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="turf_details",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
