# Generated by Django 5.1.6 on 2025-08-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0009_alter_rating_value_alter_turf_details_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf_details",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Kollam", "Kollam"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Alappuzha", "Alappuzha"),
                    ("Kottayam", "Kottayam"),
                    ("Idukki", "Idukki"),
                    ("Ernakulam", "Ernakulam"),
                    ("Thrissur", "Thrissur"),
                    ("Palakkad", "Palakkad"),
                    ("Malappuram", "Malappuram"),
                    ("Kozhikode", "Kozhikode"),
                    ("Wayanad", "Wayanad"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
