# Generated by Django 5.1.6 on 2025-08-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turf_details",
            name="status",
            field=models.CharField(
                choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                default="enabled",
                max_length=10,
            ),
        ),
    ]
