# Generated by Django 5.1.6 on 2025-08-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf_details",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="turf_images/"),
        ),
        migrations.AddField(
            model_name="turf_details",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turf_details",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
