# Generated by Django 5.1.6 on 2025-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Turfapp", "0002_turf_details_image_turf_details_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf_details",
            name="extra_features",
            field=models.TextField(
                blank=True, help_text="Any other features not listed above", null=True
            ),
        ),
        migrations.AddField(
            model_name="turf_details",
            name="has_drinking_water",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turf_details",
            name="has_floodlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="turf_details",
            name="player_capacity",
            field=models.CharField(
                blank=True,
                choices=[("5", "5's"), ("7", "7's"), ("11", "11's")],
                max_length=2,
                null=True,
            ),
        ),
    ]
